title: Jose Manuel Padilla, Game Developer
description: > # this means to ignore newlines until "baseurl:"
  Porfolio of all my works as a programmer and game developer, including those
  from my studies.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Jose Manuel Padilla # add your name
author-img: jose-manuel.jpeg # add your photo
about-author: I am a game developer, always interested in creating games. Specially interested in AI and gameplay. I've worked making projects using Unreal Engine and Unity 3D besides other projects directly in C++ and other languages using different graphic libraries. I've worked in multiple languages, including C, C++, C#, Java, Python, Javascript, Swift, Objective C and HTML to name a few, with a degree in computer science and a HND in videogame programming. # add description
social-twitter: Josema_Dev # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: padillava # add your Github handle
social-linkedin: jose-manuel-padilla-16747b214 # add your Linkedin handle
social-email: josemanuelpadillavarea@gmail.com # add your Email address

# Disqus
discus-identifier: # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
